### ISSUE TITLE
When compiling the OpenWrt-19.07 routing firmware and synchronously updating the rp-pppoe code to the latest, an error is displayed!

### ISSUE THREAD

**Issue by openwrtdiy** [dfskoll/rp-pppoe#12]
Type 'make install' as root to install the software.
mkdir -p /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 pppoe /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 pppoe-server /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
if test -x pppoe-relay ; then /usr/bin/install -c -m 755 pppoe-relay /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin; fi
if test -x pppoe-sniff; then /usr/bin/install -c -m 755 pppoe-sniff /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin; fi
/usr/bin/install -c -m 755 ../scripts/pppoe-connect /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 ../scripts/pppoe-start /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 ../scripts/pppoe-status /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 ../scripts/pppoe-stop /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
/usr/bin/install -c -m 755 ../scripts/pppoe-setup /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/sbin
mkdir -p /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install -c -m 644 ../doc/CHANGES /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install -c -m 644 ../doc/KERNEL-MODE-PPPOE /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install -c -m 644 ../doc/HOW-TO-CONNECT /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install -c -m 644 ../doc/LICENSE /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install -c -m 644 ../README /home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/ipkg-install/usr/share/doc/rp-pppoe-3.15
/usr/bin/install: cannot stat '../README': No such file or directory
Makefile:151: recipe for target 'install' failed
make[4]: *** [install] Error 1
make[4]: Leaving directory '/home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/src'
Makefile:148: recipe for target '/home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/.built' failed
make[3]: *** [/home/kokang/openwrtdiy/build_dir/target-x86_64_musl/rp-pppoe-2022.04.24/.built] Error 2
make[3]: Leaving directory '/home/kokang/openwrtdiy/feeds/packages/net/rp-pppoe'
time: package/feeds/packages/rp-pppoe/compile#3.71#1.63#6.74
package/Makefile:111: recipe for target 'package/feeds/packages/rp-pppoe/compile' failed
make[2]: *** [package/feeds/packages/rp-pppoe/compile] Error 2
make[2]: Leaving directory '/home/kokang/openwrtdiy'
package/Makefile:107: recipe for target '/home/kokang/openwrtdiy/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/kokang/openwrtdiy/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kokang/openwrtdiy'
/home/kokang/openwrtdiy/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by openwrtdiy** [comment]
https://github.com/openwrtdiy/packages/blob/openwrt-19.07/net/rp-pppoe/Makefile

#
# Copyright (C) 2006-2022 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=rp-pppoe
PKG_VERSION:=2022.04.24
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/dfskoll/rp-pppoe.git
PKG_SOURCE_VERSION:=45c898c6426c50642a21cf477b94eb4c1397bd0a
PKG_HASH:=b6077dc170ce66c30416bef3bd24d3d2c84433cd7371fb815c31d987191b57fd

PKG_MAINTAINER:=
PKG_LICENSE:=LGPL-2.0-or-later
PKG_LICENSE_FILES:=doc/LICENSE
PKG_CPE_ID:=cpe:/a:roaring_penguin:pppoe

PKG_BUILD_DEPENDS:=ppp
PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Package/rp-pppoe/Default
  SECTION:=net
  CATEGORY:=Network
  TITLE:=PPPoE (PPP over Ethernet)
  URL:=https://dianne.skoll.ca/projects/rp-pppoe/
  SUBMENU:=Dial-in/up
endef

define Package/rp-pppoe/Default/description
  Dubbed RP-PPPoE, this open-source product is ideal for Linux users with
  a DSL "modem" whose Internet service provider uses PPPoE.
endef

define Package/rp-pppoe-common
  $(call Package/rp-pppoe/Default)
  TITLE+= common
  DEPENDS:=ppp
endef

define Package/rp-pppoe-common/description
$(call Package/rp-pppoe/Default/description)

 This package contains files common to server and relay.
endef

define Package/rp-pppoe-common/conffiles
/etc/config/pppoe
endef

define Package/rp-pppoe-relay
  $(call Package/rp-pppoe/Default)
  DEPENDS:=+rp-pppoe-common
  TITLE+= relay
  DEFAULT:=n
endef

define Package/rp-pppoe-relay/description
$(call Package/rp-pppoe/Default/description)

 This package contains pppoe-relay.
endef

define Package/rp-pppoe-relay/conffiles
/etc/default/pppoe-relay
endef

define Package/rp-pppoe-server
  $(call Package/rp-pppoe/Default)
  DEPENDS:=+rp-pppoe-common +ppp-mod-pppoe
  TITLE+= server
endef

define Package/rp-pppoe-server/conffiles
/etc/ppp/pppoe-server-options
/etc/ppp/options
/etc/ppp/pap-secrets
/etc/ppp/chap-secrets
/etc/default/pppoe-server
endef

define Package/rp-pppoe-server/description
$(call Package/rp-pppoe/Default/description)

 This package contains pppoe-server.
endef

define Package/rp-pppoe-sniff
  $(call Package/rp-pppoe/Default)
  DEPENDS:=+ppp @BROKEN
  TITLE+= sniffer
endef

define Package/rp-pppoe-sniff/description
$(call Package/rp-pppoe/Default/description)

 This package contains pppoe-sniff.
endef

TARGET_CFLAGS += -I$(PKG_BUILD_DIR)/src/libevent -isystem $(PKG_BUILD_DIR)/missing-headers -D_BSD_SOURCE
CONFIGURE_PATH := ./src
CONFIGURE_ARGS += ac_cv_path_PPPD=/usr/sbin/pppd --enable-plugin=$(STAGING_DIR)/usr/include/
MAKE_FLAGS := DESTDIR="$(PKG_INSTALL_DIR)" PLUGIN_PATH=pppoe.so install
MAKE_PATH := ./src

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)/missing-headers/net
	$(CP) ./files/ppp_defs.h $(PKG_BUILD_DIR)/missing-headers/net/
	$(call Build/Prepare/Default,$(1),$(2),$(3))
endef

define Package/rp-pppoe-common/install
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_CONF) ./files/pppoe.config $(1)/etc/config/pppoe
endef

define Package/rp-pppoe-relay/install
	$(INSTALL_DIR) $(1)/etc/init.d $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./files/pppoe-relay.init $(1)/etc/init.d/pppoe-relay
	$(INSTALL_DIR) $(1)/usr/sbin
	$(CP) $(PKG_INSTALL_DIR)/usr/sbin/pppoe-relay $(1)/usr/sbin/
	$(INSTALL_DATA) ./files/pppoe-relay.default $(1)/etc/uci-defaults/
endef

define Package/rp-pppoe-server/install
	$(INSTALL_DIR) $(1)/etc/init.d $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./files/pppoe-server.init $(1)/etc/init.d/pppoe-server
	$(INSTALL_DIR) $(1)/etc/ppp
	$(INSTALL_CONF) ./files/ppp/{options,pap-secrets,pppoe-server-options} $(1)/etc/ppp/
	$(INSTALL_DIR) $(1)/etc/ppp/plugins
	$(INSTALL_DIR) $(1)/usr/sbin
	$(CP) $(PKG_INSTALL_DIR)/usr/sbin/pppoe-server $(1)/usr/sbin/
	$(INSTALL_DATA) ./files/pppoe-server.default $(1)/etc/uci-defaults/
endef

define Package/rp-pppoe-sniff/install
	$(INSTALL_DIR) $(1)/usr/sbin
	$(CP) $(PKG_INSTALL_DIR)/usr/sbin/pppoe-sniff $(1)/usr/sbin/
endef

$(eval $(call BuildPackage,rp-pppoe-common))
$(eval $(call BuildPackage,rp-pppoe-relay))
$(eval $(call BuildPackage,rp-pppoe-server))
$(eval $(call BuildPackage,rp-pppoe-sniff))

**Comment by openwrtdiy** [comment]
Found the reason! There are two errors:
1. Rename README.md to README
https://github.com/openwrtdiy/rp-pppoe/commit/8e5f93b2686a574fe26a024f386d532e0a769172

2. There is one less file SERVPOET when compiling
https://github.com/openwrtdiy/rp-pppoe/commit/5288ee61239ec543aa2d157eddca81f29c38cf1b

**Comment by dfskoll** [comment]
Thanks!  Fixed in https://github.com/dfskoll/rp-pppoe/commit/dc7e00a1523479552528503bad032de3068da939
