### ISSUE TITLE
PADT on PADO timeout feature request

### ISSUE THREAD

**Issue by fluteze** [dfskoll/rp-pppoe#28]
Could you please add the ability to trigger a PADT if PADO/PADI times out?
My ISP uses a Cisco access concentrator that will become very quiet for 30 or more minutes after too many PADI/PADO failures happen until/unless a PADT is sent. I'm using RP-PPPoE from the OpenWRT project, current stable as of this post.

**Comment by dfskoll** [comment]
I don't see how that's possible.  Until the client has received a PADS with a session number in it, what session would we put in the PADT?

**Comment by fluteze** [comment]
The ISP's machine doesn't care about the session number, all 0's work just fine, it just wants a PADT from the right Ethernet address. I know it doesn't match the spec, but it's a live world application. The ISP's rentable modems do that when there is any issue starting the PPPoE portion of the handshake. The machine ID field sometimes appears relevante to the PADT triggering a reset and subsequent success.

**Comment by dfskoll** [comment]
No, I don't like this idea.  If you _really_ need to send a random PADT, you can do it with something like:

`pppoe -I eth0 -k -e 0:mac`  where `mac` is the MAC address of the access concentrator.

It seems way too niche and hacky to actually add it as a feature to the rp-pppoe software itself.

**Comment by dfskoll** [comment]
Expanding on my previous answer... it seems to me you can script the functionality you need using the existing `pppoe -k` option.

**Comment by dfskoll** [comment]
One more thing... if the PADO is never received, how would the client know the MAC address of the PPPoE access concentrator?  The PADT packet can't be a broadcast packet; it has to be a unicast Ethernet packet.  So no, can't happen.

**Comment by fluteze** [comment]
Additional tags for the search engines:
Telmex
Cisco DSL fiber VLAN PADI non responsive timeout.
Workaround suggestion.
Broadcast PADT not following protocol.
Please leave the request in "completed" status.
