### ISSUE TITLE
Log Stdout

### ISSUE THREAD

**Issue by mayconrcmello** [dfskoll/rp-pppoe#31]
I compiled rp-pppoe version 4 against pppd version 2.5.0 and I'm encountering issues with the client connection. The log output is not clear about the exact problem. Here's an example:

pppoe-server[107684]: Session 33 created for client bc:24:11:04:cf:a9 (100.103.0.36) on ens18 using Service-Name ''
pppd[107684]: Plugin /etc/ppp/plugins/rp-pppoe.so loaded.
pppd[107684]: RP-PPPoE plugin version 4.0 compiled against pppd 2.5.0
pppd[107684]: Plugin /usr/local/lib/pppd/2.5.0/radius.so loaded.
pppd[107684]: RADIUS plugin initialized.
pppd[107684]: Plugin /usr/local/lib/pppd/2.5.0/radattr.so loaded.
pppd[107684]: RADATTR plugin initialized.
pppd[107684]: pppd 2.5.0 started by root, uid 0
pppd[107684]: Connected to bc:24:11:04:cf:a9 via interface ens18
pppd[107684]: using channel 128
pppd[107684]: Using interface ppp0
pppd[107684]: Connect: ppp0 <--> ens18
pppd[107684]: sent [LCP ConfReq id=0x1 <mru 1492> <auth pap> <magic 0x74c2651a>]
pppd[107684]: rcvd [LCP ConfAck id=0x1 <mru 1492> <auth pap> <magic 0x74c2651a>]
pppd[107684]: rcvd [LCP ConfReq id=0x1 <mru 1492> <magic 0xa2569440>]
pppd[107684]: sent [LCP ConfAck id=0x1 <mru 1492> <magic 0xa2569440>]
pppd[107684]: sent [LCP EchoReq id=0x0 magic=0x74c2651a]
pppd[107684]: rcvd [LCP EchoReq id=0x0 magic=0xa2569440]
pppd[107684]: sent [LCP EchoRep id=0x0 magic=0x74c2651a]
pppd[107684]: rcvd [PAP AuthReq id=0x1 user="0511774" password=<hidden>]
pppd[107684]: sent [PAP AuthNak id=0x1 "RADIUS: Can't read config file /etc/radcli/radiusclient.conf"]
pppd[107684]: PAP peer authentication failed for 0511774
pppd[107684]: sent [LCP TermReq id=0x2 "Authentication failed"]
pppd[107684]: rcvd [LCP EchoRep id=0x0 magic=0xa2569440]
pppd[107684]: rcvd [LCP TermReq id=0x2 "Failed to authenticate ourselves to peer"]
pppd[107684]: sent [LCP TermAck id=0x2]
pppd[107684]: rcvd [LCP TermAck id=0x2]
pppd[107684]: Connection terminated.
pppd[107684]: Fatal signal 11
pppoe-server[23464]: Session 33 closed for client bc:24:11:04:cf:a9 (100.103.0.36) on ens18
pppoe-server[23464]: Sent PADT

Especially in this section:

pppd[107684]: sent [PAP AuthNak id=0x1 "RADIUS: Can't read config file /etc/radcli/radiusclient.conf"]

I believe it might be related to a dictionary attribute, but it's not reporting as previous versions did.

The pppd package is not clearly indicating where the error is occurring, making it difficult to diagnose the issue.

**Comment by dfskoll** [comment]
This isn't an rp-pppoe issue.  It has to do with the RADIUS authentication plugin of pppd; you'll need to open the issue there.  I suggest opening it at https://github.com/ppp-project/ppp

**Comment by jkroonza** [comment]
I know it's not pppoe, but this has already been fixed in ppp project in master.  Gentoo carries a patch set which I highly recommend you apply locally, it includes various rather critical fixes, 2.5.0 should not be used in any production capacity *in my personal opinion* without those additional fixes.

Gentoo patchset at https://github.com/gentoo/gentoo/tree/master/net-dialup/ppp/files

You probably need/want everything starting with 2.5.0 in there (6 of them currently).
