### ISSUE TITLE
After installed PPPoE Server in Ubntu https://src.fedoraproject.org/repo/pkgs/rp-pppoe/rp-pppoe-4.0.tar.gz/ while runing PPPOE Server getting error "pppoe: ioctl(SIOCGIFHWADDR): No such device" Any one help me on this issue.

### ISSUE THREAD

**Issue by Challasaibaba** [dfskoll/rp-pppoe#33]
After installed PPPoE Server in Ubntu https://src.fedoraproject.org/repo/pkgs/rp-pppoe/rp-pppoe-4.0.tar.gz/ while running PPPOE Server getting error like "pppoe: ioctl(SIOCGIFHWADDR): No such device" Any one help me on this issue.

Apr 25 19:08:55 rnd-test systemd[1]: Stopped =PPPoE-Server.
Apr 25 19:08:55 rnd-test systemd[1]: Started =PPPoE-Server.
Apr 25 19:08:55 rnd-test pppoe-server[13517]: pppoe: ioctl(SIOCGIFHWADDR): No such device
Apr 25 19:08:55 rnd-test pppoe-server[13517]: ioctl(SIOCGIFHWADDR): No such device
Apr 25 19:08:55 rnd-test systemd[1]: pppoe.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 19:08:55 rnd-test systemd[1]: pppoe.service: Failed with result 'exit-code'.
Apr 25 19:08:55 rnd-test systemd[1]: pppoe.service: Scheduled restart job, restart counter is at 5.
Apr 25 19:08:55 rnd-test systemd[1]: Stopped =PPPoE-Server.
Apr 25 19:08:55 rnd-test systemd[1]: pppoe.service: Start request repeated too quickly.
Apr 25 19:08:55 rnd-test systemd[1]: pppoe.service: Failed with result 'exit-code'.
Apr 25 19:08:55 rnd-test systemd[1]: Failed to start =PPPoE-Server.
Apr 25 19:08:56 rnd-test geoclue[1330]: Failed to query location: Error resolving “location.services.mozilla.com”: Temporary failure in name resolution
Apr 25 19:09:00 rnd-test systemd[1]: Starting Clean php session files...
Apr 25 19:09:00 rnd-test systemd[1]: phpsessionclean.service: Deactivated successfully.
Apr 25 19:09:00 rnd-test systemd[1]: Finished Clean php session files.
Apr 25 19:09:01 rnd-test CRON[13589]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)

sudo systemctl restart pppoe.service 
rnd-test@rnd-test:/etc/systemd/system$ sudo systemctl status pppoe.service 
× pppoe.service - =PPPoE-Server
     Loaded: loaded (/etc/systemd/system/pppoe.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-04-25 19:15:37 IST; 4s ago
    Process: 14303 ExecStart=/usr/sbin/pppoe-server (code=exited, status=1/FAILURE)
   Main PID: 14303 (code=exited, status=1/FAILURE)
        CPU: 3ms

Apr 25 19:15:37 rnd-test systemd[1]: pppoe.service: Scheduled restart job, restart counter is at 5.
Apr 25 19:15:37 rnd-test systemd[1]: Stopped =PPPoE-Server.
Apr 25 19:15:37 rnd-test systemd[1]: pppoe.service: Start request repeated too quickly.
Apr 25 19:15:37 rnd-test systemd[1]: pppoe.service: Failed with result 'exit-code'.
Apr 25 19:15:37 rnd-test systemd[1]: Failed to start =PPPoE-Server.

**Comment by jkroonza** [comment]
1.  Please fix your DNS ... won't stop pppoe-server from working but other things may well break.
2.  You need to pass the correct -I to pppoe-server for it to work, you probably just need to edit the .service or it's configuration file.

This is not a rp-pppoe issue so I'm going to close.
