### ISSUE TITLE
modprobe modules in configure.ac?

### ISSUE THREAD

**Issue by genbtc** [dfskoll/rp-pppoe#34]
https://github.com/dfskoll/rp-pppoe/blob/master/src/configure.ac#L136

these modprobe statements in the configure.ac are redundant - the package still needs to be built for containers that can't modprobe, or for local user without elevation, and when it can modprobe, the unexpected modules loaded leads to a breach of security policy in my environment.
Theres got to be a better way, we are locking configure scripts down.

-Thanks

**Comment by jkroonza** [comment]
Agreed.  And modprobe will generally only be available to root anyway.

I suggest just removing them and moving on.

@dfskoll do we actually *need* to test the kernel?  We're proceeding to build the kernel stuff regardless, so I guess merely testing that the relevant #define constants are available is good enough.

**Comment by dfskoll** [comment]
Oh, yeah, those modprobes should go.  They're ancient cruft from simpler times, and when I didn't really know what I was doing.  @jkroonza do you want to take a crack at it, or do you want me too?  I currently seem to have come down with COVID and feel awful, so I probably won't look at this for about a week.
