### ISSUE TITLE
where is the option "MaxSessionsPerUser"?

### ISSUE THREAD

**Issue by Hylio** [dfskoll/rp-pppoe#36]
Hello. i do some work on the rp-pppoe-server ver3.14, in my own router with linux system. I want to know if the newest code have the option "MaxSessionsPerUser"? i dont find it in pppoe-server.c.
and, does this option work in 3.14? i dont find where this options is used in the code .

**Comment by dfskoll** [comment]
Hi,

There is no such option in rp-pppoe.  You can limit the number of sessions per client MAC with the "-x" command-line option, but there's no option for limiting the number of sessions per user.

Regards,

Dianne.
